apiVersion: batch/v1
kind: Job
metadata:
  name: mirror-dk-service-once
spec:
  template:
    spec:
      hostNetwork: true
      # force this Pod onto ECU-A (your Internet-capable node)
      nodeSelector:
        kubernetes.io/hostname: xip  
      restartPolicy: Never
      containers:
      - name: mirror
        # use a container with skopeo or crane installed
        image: quay.io/containers/skopeo:latest
        command: ["skopeo","copy"]
        args:
          - "--retry-times=3"
          - "--all"
          - "--dest-tls-verify=false"
          - "docker://ghcr.io/eclipse-autowrx/dk_service_can_provider:latest"
          - "docker://localhost:5000/eclipse-autowrx/dk_service_can_provider:latest"
