apiVersion: apps/v1
kind: Deployment
metadata:
  name: dk-service-can-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dk-service-can-provider
  template:
    metadata:
      labels:
        app: dk-service-can-provider
    spec:
      nodeSelector:
        kubernetes.io/hostname: s32g274ardb2 # <--- Name of your agent node
      hostNetwork: true                  # --network host
      containers:
      - name: dk-service-can-provider
        image: ghcr.io/eclipse-autowrx/dk_service_can_provider:latest
        securityContext:
          privileged: true               # --privileged
        # If your container needs to run interactively, add TTY and stdin
        tty: true
        stdin: true
        # Kubernetes logging is handled by the cluster, not container log options
        # --log-opt is not needed/used in Kubernetes
