apiVersion: apps/v1
kind: Deployment
metadata:
  name: 6878e120946463a9a7d6d541
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: 6878e120946463a9a7d6d541
  template:
    metadata:
      labels:
        app: 6878e120946463a9a7d6d541
    spec:
      nodeSelector:
        kubernetes.io/hostname: vip
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      
      containers:
      - name: 6878e120946463a9a7d6d541
        image: ghcr.io/ync1hc/dk_service_can_provider:latest
        imagePullPolicy: IfNotPresent
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        
        env:
            - name: CAN_PORT
              value: "can0"
            - name: KUKSA_ADDRESS
              value: "192.168.56.48"
            - name: MAPPING_FILE
              value: "mapping/vss_4.0/vss_dbc.json"

        
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          allowPrivilegeEscalation: false
        
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-tmp
          mountPath: /var/tmp
      
      volumes:
      - name: tmp
        emptyDir: {}
      - name: var-tmp
        emptyDir: {}
