apiVersion: apps/v1
kind: Deployment
metadata:
  name: 6890a3afe4bb77b728f898be
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: 6890a3afe4bb77b728f898be
  template:
    metadata:
      labels:
        app: 6890a3afe4bb77b728f898be
    spec:
      nodeSelector:
        kubernetes.io/hostname: vip
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      
      containers:
      - name: 6890a3afe4bb77b728f898be
        image: ghcr.io/samtranbosch/dk_service_can_provider:latest
        imagePullPolicy: IfNotPresent
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        
        env:
        - name: SERVER_TYPE
          value: "kuksa_databroker"
        - name: CAN_PORT
          value: "can1"
        - name: KUKSA_ADDRESS
          value: "192.168.56.48"
        - name: MAPPING_FILE
          value: "mapping/vss_4.0/vss_dbc.json"
        
        args: []
        
        securityContext:
          privileged: true
        
        tty: true
        stdin: true
        
        volumeMounts:
        - name: dev
          mountPath: /dev
      
      volumes:
      - name: dev
        hostPath: 
          path: /dev
          type: Directory
