apiVersion: batch/v1
kind: Job
metadata:
  name: sdv-runtime-pull
spec:
  template:
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: xip
      restartPolicy: Never
      containers:
      - name: sdv-runtime-pull
        image: ghcr.io/eclipse-autowrx/sdv-runtime:latest
        imagePullPolicy: Always
        command: ["true"]
